name = "lustre"
version = "3.1.2"

description = "An Elm-inspired framework for building web apps in Gleam!"
licences = ["MIT"]
repository = { type = "github", user = "lustre-labs", repo = "lustre" }
links = [
  { title = "Website", href = "https://lustre.build" },
  { title = "Sponsor", href = "https://github.com/sponsors/hayleigh-dot-dev" },
]
gleam = ">= 0.33.0"

internal_modules = [
  "lustre/try",
]

[dependencies]
gleam_stdlib = "~> 0.34"
gleam_community_ansi = "~> 1.3"
glint = "~> 0.14"
argv = "~> 1.0"
